#!/bin/bash
APPLICATION=""

function install(){
    # 将当前文件cp一份到/etc/init.d/下
    cp $(pwd)/${0} /etc/init.d 
    # 添加可执行权限
    chmod +x /etc/init.d/${0}
    # 设置开机启动
    chkconfig /etc/init.d/${0} on 
    # 设置服务运行级别
    chkconfig --add /etc/init.d/${0}
    # 安装mysql
    wget "https://raw.githubusercontent.com/Hepc622/Shell/master/config/config.cf"
    if [[ -f 'config.cf' ]]; then
        # read config file
        for LINE in $(cat config.cf)
        do
            # Is contains fastdfs
            if [[ -n $(echo ${LINE}|grep '^activitymq=') ]]; then
                OLD_IFS=${IFS}
                # deal 
                IFS='=' 
                ARR=(${LINE})
                IFS=","
                URLS=(${ARR[1]})
                IFS=${OLD_IFS}
            fi
        done
    else
        echo "get config file faild"
        exit 0
    fi
    # clear config.cf file
    rm -f config.cf
    
    # Execcut every one script
    for URL in ${URLS[@]}; do
        URL=${URL##\"}
        URL=${URL%%\"}
        # 截取出安装包名字
        FILENAME=${URL##*/}
        if [[ ! -f /usr/local/src/$FILENAME ]]; then
          # Try to take the script
          wget ${URL} -P /usr/local/src
        fi
        # 解压文件
        tar -zxvf /usr/local/src/${FILENAME} -C /usr/local/src/

        # 获取文件夹名字
        app_name=$(ls -l | grep 'activemq'| grep 'drwxr' | awk '{print $9}')
        app_path=/usr/local/src/${app_name}
        # 切入到文件夹
        cd ${app_path}
        # cd 到bin
        cd bin
        APPLICATION=${app_path}/bin/activemq
    done
    if [[ -z iptables -L -n|grep 61616 ]]; then
        #statements
        iptables -I OUTPUT -p udp -m state --state NEW -m udp --dport 61616 -j ACCEPT
        iptables -I OUTPUT -p tcp -m state --state NEW -m tcp --dport 61616 -j ACCEPT

        iptables -I OUTPUT -p udp -m state --state NEW -m udp --dport 61616 -j ACCEPT
        iptables -I OUTPUT -p tcp -m state --state NEW -m tcp --dport 61616 -j ACCEPT

        service iptables save
    fi
    if [[ -z iptables -L -n|grep 8161 ]]; then
        #statements
        iptables -I OUTPUT -p udp -m state --state NEW -m udp --dport 8161 -j ACCEPT
        iptables -I OUTPUT -p tcp -m state --state NEW -m tcp --dport 8161 -j ACCEPT

        iptables -I OUTPUT -p udp -m state --state NEW -m udp --dport 8161 -j ACCEPT
        iptables -I OUTPUT -p tcp -m state --state NEW -m tcp --dport 8161 -j ACCEPT

        service iptables save
    fi
}
function start(){
    ${APPLICATION} start
}
function stop(){
    ${APPLICATION} stop   
}
function status(){
    ${APPLICATION} status
}
function restart(){
    ${APPLICATION} restart   
}
function help(){
  echo "使用方法: redis [start|stop|status|restart|help]"
  echo "start:启动activitymq程序"
  echo "stop:暂停activitymq程序"
  echo "status:查看程序运行状态"
  echo "restart:重启程序"
  echo "help:打印帮助信息"
}
case $1 in
    'install')
        install
    ;;
    'start')
        start
    ;;
    'stop')
        stop
    ;;
    'restart')
        start
    ;;
    'status')
        status
    ;;
    'help')
        help
    ;;
  *)

esac
exit 0